language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install libpoco-dev

notifications:
  email: false
  irc:
    channels:
      - "irc.badnik.net#pso2"
    on_success: change
    on_failure: change


script: cmake . && make
